# .github/workflows/release.yaml

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release windows/amd64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.21
      - name: Build
        run: go build -o "automover-windows-amd64.exe" .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.exe"
